meta_product_name: "Open Rehearsal"
meta_title: "Open Rehearsal | Get together and play the music you love"
meta_description: "Open Rehearsal is your new social music-making app. Connect easily with local musicians for informal rehearsal sessions."
meta_image: "og-image.png"
